# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

font_family 0xProto Nerd Font
font_size 12.0

cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.8

mouse_hide_wait -1

visual_bell_duration 0.5

background #000000
foreground #dfdfdd
selection_foreground #000000
selection_background #eebebe
background_opacity 1.0

confirm_os_window_close 0

color0 #000000
color1 #e78284
color2 #b6e0a4
color3 #fab387
color4 #9fcbfc
color5 #c8a4e0
color6 #9bbfbf
color7 #dfdfdd

color8 #6a707f
color9 #eebebe
color10 #b6e0a4
color11 #e0d8a4
color12 #9fcbfc
color13 #c8a4e0
color14 #9bbfbf
color15 #dfdfdd
