# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

confirm_os_window_close 0
single_instance yes
allow_remote_control socket-only
listen_on unix:/tmp/mykitty

font_family      0xProto Nerd Font
font_size        12.0

# Bell
enable_audio_bell no
visual_bell_duration 0.5

# Cursor
cursor_shape          beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.8
cursor_trail          3

# Mouse
mouse_hide_wait 3.0

# Zoom: current window only
map ctrl+equal change_font_size current +1.0
map ctrl+minus change_font_size current -1.0
map ctrl+0     change_font_size current 0

# Disable ctrl+tab and shift+tab
map ctrl+tab  no_op
map shift+tab no_op

# Window
background_opacity 1.0

# Colors
selection_foreground #000000
selection_background #eebebe
background          #000000
foreground          #dfdfdd

# Normal colors
color0  #000000
color1  #e78284
color2  #b6e0a4
color3  #fab387
color4  #9fcbfc
color5  #c8a4e0
color6  #9bbfbf
color7  #dfdfdd

# Bright colors
color8  #6a707f
color9  #eebebe
color10 #b6e0a4
color11 #e0d8a4
color12 #9fcbfc
color13 #c8a4e0
color14 #9bbfbf
color15 #dfdfdd
