# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

font=0xProto Nerd Font:size=12
resize-delay-ms=0

[bell]
visual=yes

[cursor]
beam-thickness=1.5
blink-rate=800
style=beam
blink=yes

[mouse]
alternate-scroll-mode=yes
hide-when-typing=yes

[colors-dark]
selection-foreground=000000
selection-background=eebebe
background=000000
foreground=dfdfdd
flash-alpha=0.1
alpha-mode=all
flash=e78284
alpha=1.0

# Normal/regular colors (color palette 0-7)
 regular0=000000  # black
 regular1=e78284  # red
 regular2=b6e0a4  # green
 regular3=fab387  # yellow
 regular4=9fcbfc  # blue
 regular5=c8a4e0  # magenta
 regular6=9bbfbf  # cyan
 regular7=dfdfdd  # white

# Bright colors (color palette 8-15)
 bright0=6a707f   # bright black
 bright1=eebebe   # bright red
 bright2=b6e0a4   # bright green
 bright3=e0d8a4   # bright yellow
 bright4=9fcbfc   # bright blue
 bright5=c8a4e0   # bright magenta
 bright6=9bbfbf   # bright cyan
 bright7=dfdfdd   # bright white

# Sixel colors
 sixel0 =  000000
 sixel1 =  9fcbfc
 sixel2 =  e78284
 sixel3 =  b6e0a4
 sixel4 =  c8a4e0
 sixel5 =  9bbfbf
 sixel6 =  e0d8a4
 sixel7 =  6a707f
 sixel8 =  20242a
 sixel9 =  9fcbfc
 sixel10 = e78284
 sixel11 = b6e0a4
 sixel12 = c8a4e0
 sixel13 = 9bbfbf
 sixel14 = e0d8a4
 sixel15 = dfdfdd
