# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = killall hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on && hyprlock &
}

listener {
    timeout = 300
    on-timeout = hyprlock
}

listener {
    timeout = 300
        on-timeout = solaar config "G515 TKL" brightness_control 0
        on-resume = solaar config "G515 TKL" brightness_control 100
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}   
