# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

theme = "kripton"

client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
client_id = "d420a117a32841c2b3474932e49fb54b"
playback_format = """
{status}  {track}  󰇙  {artists}  {liked}
{album}  {genres}
{metadata}"""
playback_metadata_fields = [
    "repeat",
    "shuffle",
    "volume",
]
playback_refresh_duration_in_ms = 0
sort_artist_albums_by_type = false
default_device = "spotify-player"
progress_bar_position = "Bottom"
app_refresh_duration_in_ms = 32
enable_cover_image_cache = true
progress_bar_type = "Rectangle"
notify_streaming_only = false
enable_media_control = true
enable_streaming = "Always"
tracks_playback_limit = 50
notify_timeout_in_secs = 0
notify_transient = false
page_size_in_rows = 10
seek_duration_secs = 5
cover_img_scale = 0.0
border_type = "Plain"
enable_notify = true
cover_img_length = 0
cover_img_width = 4
explicit_icon = "󰯹"
liked_icon = ""
pause_icon = ""
play_icon = ""
genre_num = 2

[notify_format]
summary = "{track}"
body = "{artists}"

[layout]
playback_window_position = "Top"
playback_window_height = 0

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "spotify-player"
device_type = "speaker"
normalization = true
audio_cache = true
autoplay = true
bitrate = 320
volume = 100
