# ┌─┐┌─┐┌┐┌┬ ┬┌─┐┬─┐┬┌─┌─┐
# ┌─┘├┤ │││││││ │├┬┘├┴┐└─┐
# └─┘└─┘┘└┘└┴┘└─┘┴└─┴ ┴└─┘
# https://github.com/kbuckleys/

[[themes]]
name = "kripton"

[themes.component_style]
playback_progress_bar = { fg = "#b6e0a4", bg = "#20242a" }

current_playing = { fg = "#000000", bg = "#b6e0a4", modifiers = ["Bold"] }
selection = { fg = "#000000", bg = "#dfdfdd", modifiers = ["Bold"] }

lyrics_playing = { fg = "#b6e0a4", modifiers = ["Bold"] }
lyrics_played = { fg = "#6a707f"}

page_desc = { fg = "#9bbfbf", modifiers = ["Bold"] }
playback_artists = { fg = "#b6e0a4", modifiers = ["Bold"] }
playback_status = { fg = "#b6e0a4", modifiers = ["Bold"] }
playback_track = { fg = "#b6e0a4", modifiers = ["Bold"] }
playback_metadata = { fg = "#6a707f" }
playlist_desc = { fg = "#6a707f" }
table_header = { fg = "#6a707f" }
block_title = { fg = "#6a707f" }
border = { fg = "#20242a" }
